### ISSUE TITLE
How to craft Ball Bearing?

### ISSUE THREAD

**Issue by bartaslondon** [Necro9227/Speed-Machines#2]
I'm not sure if this is right place to post an issue ( or lack of my knowledge) but I can't find anywhere how to craft a Ball Bearing. I'm using 5Dims plus few other mods.

**Comment by Necro9227** [comment]
It's a chemical plant recipe but in the newer version it's a standard assembling machine recipe and the crafting time is reduced.

**Comment by bartaslondon** [comment]
It must be some issue as I can't find it anywhere. I tried assembling machine and plant and I can't see it anywhere

**Comment by Necro9227** [comment]
Version 0.0.2 is Available and the ball bearing is unlocked as part of the new research.
if it's still not showing then you could go into the the file speed_machines/prototypes/recipes/recipes.lua and scroll down to the ball bearing and set enabling from false to true. which can be accessed in notepad

**Comment by bartaslondon** [comment]
Now it's working, thanks for your help
